import { Input, Switch, Text, useTheme } from "@nextui-org/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FaMoon, FaSearch, FaSun } from "react-icons/fa";
import styles from "../styles/Home.module.css";
import { useTheme as useNextTheme } from "next-themes";

const YourComponent = () => (
  <Image
    src="/images/profile.jpg" // Route of the image file
    height={144} // Desired size with correct aspect ratio
    width={144} // Desired size with correct aspect ratio
    alt="Your Name"
  />
);

const Home: NextPage = () => {
  const { setTheme } = useNextTheme();
  const { isDark, type } = useTheme();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="shadow-sm">
        <div className="flex items-center justify-between h-16 max-w-screen-xl px-4 mx-auto">
          <div className="flex items-center space-x-4 justify-center">
            <h1 className="flex mt-2">
              <Text
                h1
                size={40}
                css={{
                  textGradient: "45deg, $pink300 0%, $blue400 100%",
                }}
                weight="bold"
              >
                api
              </Text>
              <Text h1 size={40}>
                heim
              </Text>
            </h1>
            <div>
              <Input
                clearable
                contentRightStyling={false}
                placeholder="Search"
                contentRight={<FaSearch className="m-4" />}
              />
            </div>
          </div>

          <div className="flex justify-end flex-1 w-0 ">
            <Switch
              initialChecked={isDark}
              size="xl"
              shadow
              iconOn={<FaMoon />}
              iconOff={<FaSun />}
              onChange={(e) => setTheme(e.target.checked ? "dark" : "light")}
            />
          </div>
        </div>

        <div className="border-t border-gray-100 lg:hidden">
          <nav className="flex items-center justify-center p-4 overflow-x-auto text-sm font-medium">
            <a className="flex-shrink-0 pl-4 text-gray-900" href="">
              About
            </a>
            <a className="flex-shrink-0 pl-4 text-gray-900" href="">
              Blog
            </a>
            <a className="flex-shrink-0 pl-4 text-gray-900" href="">
              Projects
            </a>
            <a className="flex-shrink-0 pl-4 text-gray-900" href="">
              Contact
            </a>
          </nav>
        </div>
      </header>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
